#[cfg(test)]
#[test]
fn all_episodes_watched() {
    use crate::{deleterr::watched, tautulli::models::TautulliResponse};

    let tau_hist = r#"{
        "response": {
          "result": "success",
          "message": null,
          "data": {
            "recordsFiltered": 10,
            "recordsTotal": 14967,
            "data": [
              {
                "reference_id": 13291,
                "row_id": 13291,
                "id": 13291,
                "date": 1692071250,
                "started": 1692071250,
                "stopped": 1692072740,
                "duration": 1490,
                "paused_counter": 0,
                "user_id": 538225,
                "user": "omarshirazmir",
                "friendly_name": "omarshirazmir",
                "user_thumb": "https://plex.tv/users/997f99c42777e85b/avatar?c=1701351546",
                "platform": "Android",
                "product": "Plex for Android (TV)",
                "player": "SHIELD Android TV",
                "ip_address": "192.168.2.63",
                "live": 0,
                "machine_id": "4f60e410d5a5e6fd-com-plexapp-android",
                "location": "lan",
                "secure": 1,
                "relayed": 0,
                "media_type": "episode",
                "rating_key": 64069,
                "parent_rating_key": 64062,
                "grandparent_rating_key": 64061,
                "full_title": "Little Demon - Village of the Found",
                "title": "Village of the Found",
                "parent_title": "Season 1",
                "grandparent_title": "Little Demon",
                "original_title": "",
                "year": "",
                "media_index": 10,
                "parent_media_index": 1,
                "thumb": "/library/metadata/64062/thumb/1683555428",
                "originally_available_at": "2022-10-20",
                "guid": "plex://episode/6301d02ea4cb834bd4db933d",
                "transcode_decision": "direct play",
                "percent_complete": 100,
                "watched_status": 1,
                "group_count": 1,
                "group_ids": "13291",
                "state": null,
                "session_key": null
              },
              {
                "reference_id": 13289,
                "row_id": 13289,
                "id": 13289,
                "date": 1692069760,
                "started": 1692069760,
                "stopped": 1692071249,
                "duration": 1489,
                "paused_counter": 0,
                "user_id": 538225,
                "user": "omarshirazmir",
                "friendly_name": "omarshirazmir",
                "user_thumb": "https://plex.tv/users/997f99c42777e85b/avatar?c=1701351546",
                "platform": "Android",
                "product": "Plex for Android (TV)",
                "player": "SHIELD Android TV",
                "ip_address": "192.168.2.63",
                "live": 0,
                "machine_id": "4f60e410d5a5e6fd-com-plexapp-android",
                "location": "lan",
                "secure": 1,
                "relayed": 0,
                "media_type": "episode",
                "rating_key": 64065,
                "parent_rating_key": 64062,
                "grandparent_rating_key": 64061,
                "full_title": "Little Demon - Wet Bodies",
                "title": "Wet Bodies",
                "parent_title": "Season 1",
                "grandparent_title": "Little Demon",
                "original_title": "",
                "year": "",
                "media_index": 9,
                "parent_media_index": 1,
                "thumb": "/library/metadata/64062/thumb/1683555428",
                "originally_available_at": "2022-10-13",
                "guid": "plex://episode/6301d02ea4cb834bd4db932d",
                "transcode_decision": "direct play",
                "percent_complete": 99,
                "watched_status": 1,
                "group_count": 1,
                "group_ids": "13289",
                "state": null,
                "session_key": null
              },
              {
                "reference_id": 13165,
                "row_id": 13165,
                "id": 13165,
                "date": 1691557550,
                "started": 1691557550,
                "stopped": 1691558904,
                "duration": 1354,
                "paused_counter": 0,
                "user_id": 538225,
                "user": "omarshirazmir",
                "friendly_name": "omarshirazmir",
                "user_thumb": "https://plex.tv/users/997f99c42777e85b/avatar?c=1701351546",
                "platform": "Android",
                "product": "Plex for Android (TV)",
                "player": "SHIELD Android TV",
                "ip_address": "192.168.2.63",
                "live": 0,
                "machine_id": "4f60e410d5a5e6fd-com-plexapp-android",
                "location": "lan",
                "secure": 1,
                "relayed": 0,
                "media_type": "episode",
                "rating_key": 64067,
                "parent_rating_key": 64062,
                "grandparent_rating_key": 64061,
                "full_title": "Little Demon - Domestic Disturbance VIII",
                "title": "Domestic Disturbance VIII",
                "parent_title": "Season 1",
                "grandparent_title": "Little Demon",
                "original_title": "",
                "year": "",
                "media_index": 8,
                "parent_media_index": 1,
                "thumb": "/library/metadata/64062/thumb/1683555428",
                "originally_available_at": "2022-10-06",
                "guid": "plex://episode/6301d02da4cb834bd4db9314",
                "transcode_decision": "direct play",
                "percent_complete": 99,
                "watched_status": 1,
                "group_count": 1,
                "group_ids": "13165",
                "state": null,
                "session_key": null
              },
              {
                "reference_id": 12869,
                "row_id": 12869,
                "id": 12869,
                "date": 1690510805,
                "started": 1690510805,
                "stopped": 1690512162,
                "duration": 1357,
                "paused_counter": 0,
                "user_id": 538225,
                "user": "omarshirazmir",
                "friendly_name": "omarshirazmir",
                "user_thumb": "https://plex.tv/users/997f99c42777e85b/avatar?c=1701351546",
                "platform": "Android",
                "product": "Plex for Android (TV)",
                "player": "SHIELD Android TV",
                "ip_address": "192.168.2.63",
                "live": 0,
                "machine_id": "4f60e410d5a5e6fd-com-plexapp-android",
                "location": "lan",
                "secure": 1,
                "relayed": 0,
                "media_type": "episode",
                "rating_key": 64071,
                "parent_rating_key": 64062,
                "grandparent_rating_key": 64061,
                "full_title": "Little Demon - Satan's Lot",
                "title": "Satan's Lot",
                "parent_title": "Season 1",
                "grandparent_title": "Little Demon",
                "original_title": "",
                "year": "",
                "media_index": 7,
                "parent_media_index": 1,
                "thumb": "/library/metadata/64062/thumb/1683555428",
                "originally_available_at": "2022-09-29",
                "guid": "plex://episode/62e62b814a60bbaaecbbf369",
                "transcode_decision": "direct play",
                "percent_complete": 100,
                "watched_status": 1,
                "group_count": 1,
                "group_ids": "12869",
                "state": null,
                "session_key": null
              },
              {
                "reference_id": 12561,
                "row_id": 12561,
                "id": 12561,
                "date": 1689385456,
                "started": 1689385456,
                "stopped": 1689386844,
                "duration": 1388,
                "paused_counter": 0,
                "user_id": 538225,
                "user": "omarshirazmir",
                "friendly_name": "omarshirazmir",
                "user_thumb": "https://plex.tv/users/997f99c42777e85b/avatar?c=1701351546",
                "platform": "Android",
                "product": "Plex for Android (TV)",
                "player": "SHIELD Android TV",
                "ip_address": "192.168.2.63",
                "live": 0,
                "machine_id": "4f60e410d5a5e6fd-com-plexapp-android",
                "location": "lan",
                "secure": 1,
                "relayed": 0,
                "media_type": "episode",
                "rating_key": 64070,
                "parent_rating_key": 64062,
                "grandparent_rating_key": 64061,
                "full_title": "Little Demon - The Antichrist's Monster",
                "title": "The Antichrist's Monster",
                "parent_title": "Season 1",
                "grandparent_title": "Little Demon",
                "original_title": "",
                "year": "",
                "media_index": 6,
                "parent_media_index": 1,
                "thumb": "/library/metadata/64062/thumb/1683555428",
                "originally_available_at": "2022-09-22",
                "guid": "plex://episode/62e62b814a60bbaaecbbf368",
                "transcode_decision": "direct play",
                "percent_complete": 100,
                "watched_status": 1,
                "group_count": 1,
                "group_ids": "12561",
                "state": null,
                "session_key": null
              },
              {
                "reference_id": 12549,
                "row_id": 12549,
                "id": 12549,
                "date": 1689299652,
                "started": 1689299652,
                "stopped": 1689301036,
                "duration": 1384,
                "paused_counter": 0,
                "user_id": 538225,
                "user": "omarshirazmir",
                "friendly_name": "omarshirazmir",
                "user_thumb": "https://plex.tv/users/997f99c42777e85b/avatar?c=1701351546",
                "platform": "Android",
                "product": "Plex for Android (TV)",
                "player": "SHIELD Android TV",
                "ip_address": "192.168.2.63",
                "live": 0,
                "machine_id": "4f60e410d5a5e6fd-com-plexapp-android",
                "location": "lan",
                "secure": 1,
                "relayed": 0,
                "media_type": "episode",
                "rating_key": 64068,
                "parent_rating_key": 64062,
                "grandparent_rating_key": 64061,
                "full_title": "Little Demon - Night of the Leeches",
                "title": "Night of the Leeches",
                "parent_title": "Season 1",
                "grandparent_title": "Little Demon",
                "original_title": "",
                "year": "",
                "media_index": 5,
                "parent_media_index": 1,
                "thumb": "/library/metadata/64062/thumb/1683555428",
                "originally_available_at": "2022-09-15",
                "guid": "plex://episode/62e62b804a60bbaaecbbf367",
                "transcode_decision": "direct play",
                "percent_complete": 98,
                "watched_status": 1,
                "group_count": 1,
                "group_ids": "12549",
                "state": null,
                "session_key": null
              },
              {
                "reference_id": 12547,
                "row_id": 12547,
                "id": 12547,
                "date": 1689298231,
                "started": 1689298231,
                "stopped": 1689299632,
                "duration": 1401,
                "paused_counter": 0,
                "user_id": 538225,
                "user": "omarshirazmir",
                "friendly_name": "omarshirazmir",
                "user_thumb": "https://plex.tv/users/997f99c42777e85b/avatar?c=1701351546",
                "platform": "Android",
                "product": "Plex for Android (TV)",
                "player": "SHIELD Android TV",
                "ip_address": "192.168.2.63",
                "live": 0,
                "machine_id": "4f60e410d5a5e6fd-com-plexapp-android",
                "location": "lan",
                "secure": 1,
                "relayed": 0,
                "media_type": "episode",
                "rating_key": 64066,
                "parent_rating_key": 64062,
                "grandparent_rating_key": 64061,
                "full_title": "Little Demon - Popularity: Origin of Evil",
                "title": "Popularity: Origin of Evil",
                "parent_title": "Season 1",
                "grandparent_title": "Little Demon",
                "original_title": "",
                "year": "",
                "media_index": 4,
                "parent_media_index": 1,
                "thumb": "/library/metadata/64062/thumb/1683555428",
                "originally_available_at": "2022-09-08",
                "guid": "plex://episode/62e62b804a60bbaaecbbf366",
                "transcode_decision": "direct play",
                "percent_complete": 100,
                "watched_status": 1,
                "group_count": 1,
                "group_ids": "12547",
                "state": null,
                "session_key": null
              },
              {
                "reference_id": 12532,
                "row_id": 12545,
                "id": 12545,
                "date": 1689297015,
                "started": 1689204313,
                "stopped": 1689298220,
                "duration": 1403,
                "paused_counter": 0,
                "user_id": 538225,
                "user": "omarshirazmir",
                "friendly_name": "omarshirazmir",
                "user_thumb": "https://plex.tv/users/997f99c42777e85b/avatar?c=1701351546",
                "platform": "Android",
                "product": "Plex for Android (TV)",
                "player": "SHIELD Android TV",
                "ip_address": "192.168.2.63",
                "live": 0,
                "machine_id": "4f60e410d5a5e6fd-com-plexapp-android",
                "location": "lan",
                "secure": 1,
                "relayed": 0,
                "media_type": "episode",
                "rating_key": 64072,
                "parent_rating_key": 64062,
                "grandparent_rating_key": 64061,
                "full_title": "Little Demon - Everybody's Dying for the Weekend",
                "title": "Everybody's Dying for the Weekend",
                "parent_title": "Season 1",
                "grandparent_title": "Little Demon",
                "original_title": "",
                "year": "",
                "media_index": 3,
                "parent_media_index": 1,
                "thumb": "/library/metadata/64062/thumb/1683555428",
                "originally_available_at": "2022-09-01",
                "guid": "plex://episode/627fd43e1b84c2c682c354fc",
                "transcode_decision": "direct play",
                "percent_complete": 100,
                "watched_status": 1,
                "group_count": 2,
                "group_ids": "12532,12545",
                "state": null,
                "session_key": null
              },
              {
                "reference_id": 11438,
                "row_id": 11438,
                "id": 11438,
                "date": 1683600870,
                "started": 1683600870,
                "stopped": 1683602230,
                "duration": 1360,
                "paused_counter": 0,
                "user_id": 538225,
                "user": "omarshirazmir",
                "friendly_name": "omarshirazmir",
                "user_thumb": "https://plex.tv/users/997f99c42777e85b/avatar?c=1701351546",
                "platform": "Android",
                "product": "Plex for Android (TV)",
                "player": "SHIELD Android TV",
                "ip_address": "192.168.2.63",
                "live": 0,
                "machine_id": "4f60e410d5a5e6fd-com-plexapp-android",
                "location": "lan",
                "secure": 1,
                "relayed": 0,
                "media_type": "episode",
                "rating_key": 64064,
                "parent_rating_key": 64062,
                "grandparent_rating_key": 64061,
                "full_title": "Little Demon - Possession Obsession",
                "title": "Possession Obsession",
                "parent_title": "Season 1",
                "grandparent_title": "Little Demon",
                "original_title": "",
                "year": "",
                "media_index": 2,
                "parent_media_index": 1,
                "thumb": "/library/metadata/64062/thumb/1683555428",
                "originally_available_at": "2022-08-25",
                "guid": "plex://episode/627fd43e1b84c2c682c354fd",
                "transcode_decision": "direct play",
                "percent_complete": 100,
                "watched_status": 1,
                "group_count": 1,
                "group_ids": "11438",
                "state": null,
                "session_key": null
              },
              {
                "reference_id": 11433,
                "row_id": 11436,
                "id": 11436,
                "date": 1683599668,
                "started": 1683598823,
                "stopped": 1683600849,
                "duration": 1564,
                "paused_counter": 304,
                "user_id": 538225,
                "user": "omarshirazmir",
                "friendly_name": "omarshirazmir",
                "user_thumb": "https://plex.tv/users/997f99c42777e85b/avatar?c=1701351546",
                "platform": "Android",
                "product": "Plex for Android (TV)",
                "player": "SHIELD Android TV",
                "ip_address": "192.168.2.63",
                "live": 0,
                "machine_id": "4f60e410d5a5e6fd-com-plexapp-android",
                "location": "lan",
                "secure": 1,
                "relayed": 0,
                "media_type": "episode",
                "rating_key": 64063,
                "parent_rating_key": 64062,
                "grandparent_rating_key": 64061,
                "full_title": "Little Demon - First Blood",
                "title": "First Blood",
                "parent_title": "Season 1",
                "grandparent_title": "Little Demon",
                "original_title": "",
                "year": "",
                "media_index": 1,
                "parent_media_index": 1,
                "thumb": "/library/metadata/64062/thumb/1683555428",
                "originally_available_at": "2022-08-25",
                "guid": "plex://episode/609d60bb98a87a002c15344a",
                "transcode_decision": "direct play",
                "percent_complete": 100,
                "watched_status": 1,
                "group_count": 2,
                "group_ids": "11433,11436",
                "state": null,
                "session_key": null
              }
            ],
            "draw": 1,
            "filter_duration": "3 hrs 56 mins 30 secs",
            "total_duration": "3 hrs 56 mins 30 secs"
          }
        }
      }"#;

    let resp = serde_json::from_str::<TautulliResponse>(tau_hist).unwrap();

    let watched = resp.response.data.data.unwrap();
}
