version: "2.1"
services:
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/omar/Coding/docker/nginx:/config
      - /home/omar/Coding/deleterr/docker_dev/default.conf:/config/nginx/site-confs/default.conf
    network_mode: host
    restart: unless-stopped
